services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"