services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=HemoRedDB;User=root;Password=ale13426-;
    depends_on:
      - mysql
    ports:
      - "8000:80"

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ale13426-
      MYSQL_DATABASE: HemoRedDB
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: