INSERT INTO tblProvince (provinceName) VALUES
('Azua'),
('Baoruco'),
('Barahona'),
('Dajabón'),
('Duarte'),
('El Seibo'),
('Elías Piña'),
('Espaillat'),
('Hato Mayor'),
('Hermanas Mirabal'),
('Independencia'),
('La Altagracia'),
('La Romana'),
('La Vega'),
('María Trinidad Sánchez'),
('Monseñor Nouel'),
('Monte Plata'),
('Montecristi'),
('Pedernales'),
('Peravia'),
('Puerto Plata'),
('Samaná'),
('San Cristóbal'),
('San José de Ocoa'),
('San Juan'),
('San Pedro de Macorís'),
('Sánchez Ramírez'),
('Santiago'),
('Santiago Rodríguez'),
('Santo Domingo'),
('Valverde');