name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f e2e_tests/requirements.txt ]; then pip install -r e2e_tests/requirements.txt; fi
    
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
    
    - name: Set up Frontend and Backend
      run: |
        # Aquí configuras tu aplicación (en un entorno real usando Docker, por ejemplo)
        # npm install en el frontend
        # dotnet build y run en el backend
        echo "Simulación de configuración de la aplicación"
    
    - name: Run E2E Tests
      run: |
        cd e2e_tests
        python -m pytest test_cases/test_blood_request_flow.py -v
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-test-results
        path: |
          e2e_tests/reports/